### ISSUE TITLE
Non-capturing grouping and other considerations

### ISSUE THREAD

**Issue by frithnanth** [khalidelboray/PerlWeeklyChallenge#1]
I think that the non-capturing grouping square brackets aren't useful.
Also, since in the definition of token `TOP` the token `<int>` is optional, if one inputs a number in the form `.12` the program outputs an error. That may be corrected adding a default value.
One might also want to add a `+` sign to the number.
The final version of the program would be this:
```perl6
grammar Grammer {
    token TOP {<sign>? <int>? <decimal>?}
    token decimal {<dot><digit>}
    token int {<zeros>? <digit>?}
    token digit { \d+ }
    token dot { '.' }
    token zeros {0+}
    token sign {'+'}
}

my $match = Grammer.parse(@*ARGS[0]);
my $number = ($match<int><digit> // '') ~ $match<decimal>;
say $number;
```

**Comment by khalidelboray** [comment]
Thanks for opening the issue , i see that you are right about the non-capturing grouping square brackets and the error about the Nil value , the same error appears if the input is : .25 or 15 
i just added the default value as you suggested to the parts 
```perl6
grammar Grammer {
    token TOP {<sign>? <int>? [<decimal>]?}
    token decimal {<dot><digit>}
    token int {<zeros>? [<digit>]?}
    token digit { \d+ }
    token dot { '.' }
    token zeros {0+}
    token sign {'+'}
}
my $match = Grammer.parse(@*ARGS[0]);
my $number =  ($match<int><digit> // '')  ~ ($match<decimal> // '');
say $number;
```
confirm the solution to close the isuue.

**Comment by frithnanth** [comment]
Do you still need the non-capturing square brackets around <decimal> in the `TOP` definition and around <digit> int the `int` definition?

**Comment by khalidelboray** [comment]
my mistake , i forgot to remove them

**Comment by khalidelboray** [comment]
i think this is the final code 
```perl6
grammar Grammer {
    token TOP {<sign>? <int> <decimal>?}
    token decimal {<dot><digit>?}
    token int {<zeros>? <digit>?}
    token digit { \d+ }
    token dot { '.' }
    token zeros {0+}
    token sign {'+'}
}
my $match = Grammer.parse(@*ARGS[0]);
my $number =  ($match<int><digit> // '')  ~ ($match<decimal> // '');
say $number;
```
